<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Labs.Runtime.Core\Labs.Runtime.Core.csproj" />
    <ProjectReference Include="..\Labs.Runtime.Infrastructure\Labs.Runtime.Infrastructure.csproj" />
    <ProjectReference Include="..\Labs.Runtime.Application\Labs.Runtime.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
